fixed wrong var name in shortcut
Summary:
Calling FacebookAds::ad_account(123) is returning error

```
irb(main):004:0> FacebookAds::ad_account(123)
/Users/alanho/fbsource/business-sdk/sdk/servers/ruby/release/lib/facebook_ads/helpers/shortcuts.rb:26:in `ad_account': undefined local variable or method `id' for FacebookAds:Module (NameError)
        from (irb):4:in `<main>'
        from /Users/alanho/.rubies/ruby-3.0.5/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /Users/alanho/.rubies/ruby-3.0.5/bin/irb:23:in `load'
        from /Users/alanho/.rubies/ruby-3.0.5/bin/irb:23:in `<main>'
```

Reviewed By: stcheng

Differential Revision: D42953149

fbshipit-source-id: 97cb3298bd493e5ef880c768e120598f742ea215