Update shortcuts.rb
Calling 'ad_account' causes the following error. 
Believe that 'id' should be 'act_id'
```
NameError: undefined local variable or method `id' for FacebookAds:Module
```